// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCR7rWPuC7yDMq8IBX1VoUpuru4lCdVmA',
    appId: '1:567141038159:web:447c6c7934460071fe923a',
    messagingSenderId: '567141038159',
    projectId: 'smartcampusai-9fc31',
    authDomain: 'smartcampusai-9fc31.firebaseapp.com',
    storageBucket: 'smartcampusai-9fc31.firebasestorage.app',
    measurementId: 'G-0TLRH0XT5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVUL8Ef_G13ekDM3X7bbgz8hClA5Qu9l4',
    appId: '1:567141038159:android:1c222dc2a8789848fe923a',
    messagingSenderId: '567141038159',
    projectId: 'smartcampusai-9fc31',
    storageBucket: 'smartcampusai-9fc31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2tWZmZFG1s86t0sEwcDC-QUubqCCuErw',
    appId: '1:567141038159:ios:be123b9a387c88b4fe923a',
    messagingSenderId: '567141038159',
    projectId: 'smartcampusai-9fc31',
    storageBucket: 'smartcampusai-9fc31.firebasestorage.app',
    iosClientId: '567141038159-974349t49pd3cmtef30utdbn7heanhpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCampusAiPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2tWZmZFG1s86t0sEwcDC-QUubqCCuErw',
    appId: '1:567141038159:ios:be123b9a387c88b4fe923a',
    messagingSenderId: '567141038159',
    projectId: 'smartcampusai-9fc31',
    storageBucket: 'smartcampusai-9fc31.firebasestorage.app',
    iosClientId: '567141038159-974349t49pd3cmtef30utdbn7heanhpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCampusAiPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCR7rWPuC7yDMq8IBX1VoUpuru4lCdVmA',
    appId: '1:567141038159:web:aab8ce74624cdd22fe923a',
    messagingSenderId: '567141038159',
    projectId: 'smartcampusai-9fc31',
    authDomain: 'smartcampusai-9fc31.firebaseapp.com',
    storageBucket: 'smartcampusai-9fc31.firebasestorage.app',
    measurementId: 'G-60SQTC1XRB',
  );
}
